<!DOC TYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Тест</title>
</head>
<body>
Тест
    <form method="post">
      Введите ваш возраст: <input type="text" name="age" required maxlength="2" placeholder="Возраст" size="5"/><br><br>
                Выберите ваш пол: <select name="pol">
                                    <option value="man">Мужской</option>
                                    <option value="women">Женский</option>
                                  </select><br><br>
                                  <button type="submit">Посчитать</button>
    </form>
</body>
</html>